### ISSUE TITLE
Support multiple clients

### ISSUE THREAD

**Issue by mrkhatami95** [psycho-ir/fandogh#2]
Very useful project. It would be nice to support more than one service at a time. Also it would be great to give access to clients to define desired port for themselves.

**Comment by psycho-ir** [comment]
Hi @mrkhatami95,
now users with free plan can have 2 services running. 
for the time being we don't have plan to expose more than one port. however it's likely we support more than a port in next versions. 
in the mean while you can use a reverse proxy like nginx or HAproxy to have more than one service running in the same container.

**Comment by mrkhatami95** [comment]
Hi Soroosh,
Thanks for your answer.
It sounds good!
